Repository unbytes/oop, pull requests merged in 2023-06, with the labels that each got.

#38 feat(views): basic modified jframe layout
  src/views/BasicFrame.java
Labels: enhancement

#39 feat(views/home): create basic initial home layout view
  src/Main.java
  src/models/Main.java
  src/views/Home.java
Labels: enhancement

#40 feat(components/button): basic custom button layout
  src/views/components/Button.java
Labels: enhancement

#41 feat(views/home): set up home with the custom buttons
  src/views/Home.java
Labels: enhancement

#42 feat(views/basic_frame): change header layout
  src/views/BasicFrame.java
Labels: enhancement

#43 feat(views/home): add button listeners to change frame
  src/views/Home.java
Labels: enhancement

#44 feat(views/branch): initial branch frame to handle register and list
  src/views/Branch.java
Labels: enhancement

#45 feat(views/client): initial client frame to handle registration and list
  src/views/Client.java
Labels: enhancement

#48 feat(layouts/basic_frame): add footer and back button to home
  src/assets/return_white_button.png
  src/views/BasicFrame.java
  src/views/layouts/BasicFrame.java
Labels: enhancement

#46 feat(components/form): create a standard form to the project
  src/views/components/Form.java
  src/views/components/IntegerField.java
Labels: enhancement

#49 Create the login and the create Branch panel
  docs/DESIGN.md
  src/views/CreateBranch.java
  src/views/Home.java
  src/views/LoginBranch.java
  src/views/layouts/BasicFrame.java
Labels: documentation, enhancement

#50 feat(views/form): add retrieve input values method and change min size of jframe
  src/views/components/Form.java
  src/views/layouts/BasicFrame.java
Labels: enhancement

#51 feat(components/form): change return fields data type
  src/views/Client.java
  src/views/components/Form.java
Labels: enhancement

#52 feat(views/login-branch): link view to model layer with branch controller
  src/views/LoginBranch.java
  src/views/ManageBranch.java
  src/views/components/Title.java
Labels: enhancement

#53 feat(views/create-branch): link view to model layer with branch controller
  src/views/CreateBranch.java
  src/views/Home.java
Labels: enhancement

#54 feat(layouts/basic-frame): use title component to make header
  src/views/layouts/BasicFrame.java
Labels: enhancement

#55 feat(controllers/branch): start branch controller to link view and model layers
  src/controllers/BranchController.java
  src/models/Store.java
Labels: enhancement

#56 feat(login-branch): use jlist to manage branches login and implements product search
  src/Main.java
  src/views/CreateBranch.java
  src/views/Home.java
  src/views/LoginBranch.java
  src/views/ManageBranch.java
  src/views/layouts/BasicFrame.java
Labels: enhancement

#57 feat(controller/branch): create search products by word feature
  src/controllers/BranchController.java
  src/views/ManageBranch.java
Labels: enhancement

#58 docs(uml): change branch->product and client->product relationship
  diagrama_de_classes.jpeg
Labels: documentation

#59 feat(view/loginbranch): create button to delete a branch
  src/controllers/BranchController.java
  src/models/Store.java
  src/views/LoginBranch.java
Labels: enhancement

#61 feat(views/manage-branch): implements branch address update
  src/controllers/BranchController.java
  src/models/Branch.java
  src/views/ManageBranch.java
Labels: enhancement

#62 feat(views): change branch pages access flow
  src/controllers/BranchController.java
  src/views/Home.java
  src/views/LoginBranch.java
  src/views/ManageBranch.java
  src/views/Product.java
Labels: enhancement

#63 feat(views): use controller to implements crud
  src/views/Client.java
  src/views/CreateClient.java
Labels: enhancement

#64 feat(controller): add cliet crud methods from model
  src/controllers/StoreController.java
Labels: enhancement

#69 feat(product): add product, sort list of product
  src/Main.java
  src/controllers/BranchController.java
  src/models/Branch.java
  src/models/Product.java
  src/views/CreateProduct.java
  src/views/Product.java
  src/views/components/Form.java
Labels: enhancement

#70 feat(product): choose and update a product
  src/Main.java
  src/controllers/BranchController.java
  src/models/Branch.java
  src/views/CreateProduct.java
  src/views/ManageBranch.java
  src/views/Product.java
  src/views/components/Form.java
  src/views/layouts/BasicFrame.java
Labels: enhancement

#71 test(controller/branch): check branch creation and product retrieve as html template
  src/tests/Test.java
  src/tests/TestBranchController.java
Labels: enhancement

#72 feat(views/product): implements delete product function with controller
  src/controllers/BranchController.java
  src/views/Product.java
  src/views/components/IntegerField.java
Labels: enhancement

#73 create product
  src/controllers/BranchController.java
  src/models/Medicament.java
  src/models/Product.java
  src/views/CreateClient.java
  src/views/CreateProduct.java
  src/views/Product.java
  src/views/components/Form.java
Labels: enhancement

#74 test(controller/store): check delete clint store controller feature
  src/tests/TestStoreController.java
Labels: enhancement

#75 feat(store-controller): get client by cpf method
  src/controllers/StoreController.java
Labels: enhancement

#76 docs(javadocs): docs for the models and controller classes
  src/controllers/BranchController.java
  src/controllers/StoreController.java
  src/models/Client.java
  src/models/Cosmetic.java
  src/models/Medicament.java
  src/models/Product.java
  src/models/Store.java
Labels: documentation

#77 buy product and make the rest
  src/Main.java
  src/controllers/BranchController.java
  src/controllers/StoreController.java
  src/models/Branch.java
  src/models/Store.java
  src/views/ClientView.java
  src/views/CreateClient.java
  src/views/CreateProduct.java
  src/views/LoginBranch.java
  src/views/ManageBranch.java
  src/views/ProductView.java
  src/views/PurchasedProducts.java
Labels: bug, enhancement
