Repository unbytes/oop, pull requests merged in 2023-05, with the labels that each got.

#20 feat(models/branch): create branch model and correct their dependencies
  src/models/Address.java
  src/models/Branch.java
Labels: enhancement

#21 feat(models/medicament): create medicament models
  src/models/Medicament.java
Labels: enhancement

#23 docs(models/medicament): create medicament docs
  docs/DESIGN.md
Labels: documentation

#24 style(models/product): change , to ; in toString method
  src/models/Product.java
Labels: enhancement

#25 feat(models/client): remove product queue and change id -> cpf
  docs/DESIGN.md
  src/models/Client.java
Labels: documentation, enhancement

#27 feat(models/store): initial store class
  src/models/Store.java
Labels: enhancement

#28 Remove-Branch-method-added
  src/models/Store.java
Labels: enhancement

#29 feat(models/store): add listBranchFromCity method
  src/models/Store.java
Labels: enhancement

#30 feat(models/branch): buyProduct method
  docs/DESIGN.md
  src/models/Branch.java
Labels: enhancement

#31 feat(models/cosmetic): add product as inheritance
  src/models/Cosmetic.java
Labels: bug, enhancement

#32 feat(models/address): correct toString return style
  docs/DESIGN.md
  src/models/Address.java
Labels: documentation, enhancement

#33 docs(design): update store design structure
  docs/DESIGN.md
Labels: documentation

#36 docs(uml): add uml diagram to project
  README.md
  diagrama_de_classes.jpeg
Labels: documentation

#37 release(1.0.0): project models and brute tests
  .gitignore
  README.md
  diagrama_de_classes.jpeg
  docs/DESIGN.md
  src/models/Address.java
  src/models/Branch.java
  src/models/Client.java
  src/models/Cosmetic.java
  src/models/Main.java
  src/models/Medicament.java
  src/models/Product.java
  src/models/Store.java
Labels: documentation, enhancement
